### ISSUE TITLE
Using @XmlEnum to generate an enum of type Integer in json schema

### ISSUE THREAD

**Issue by jesse8888** [FasterXML/jackson-module-jaxb-annotations#33]
I just posted an issue in jackson-module-jsonSchema.

https://github.com/FasterXML/jackson-module-jsonSchema/issues/49

For completeness:

I have the following Java enum:

``` java
@XmlType
@XmlEnum(Integer.class)
public enum DefaultMessageVersion
{
    @XmlEnumValue("1") ONE;
}
```

That is producing the following json schema snippet:

``` json
"defaultMessageVersion" : {
"type" : "string",
"enum" : [ "1" ]
}
```

This is because (I believe) Jackson ignores the @XmlEnum annotation. I would like the outputted snippet to have "type" : "integer" (or int? I'm not 100% sure which it is).

I have posted the issue here at the request of cowtowncoder, and am hoping that I can submit a fix myself (with pointers on where to look), or that someone else with more knowledge and expertise can take care of it without too much trouble.

**Comment by kwinter** [comment]
What should the outcome of including @XmlEnumValue be?  We have the following:

```
@XmlEnum(Integer.class)
public enum RecommendationType
{
  @XmlEnumValue("1")
  SUGGESTED_CANDIDATES(1),
  @XmlEnumValue("2")
  SUGGESTED_RECRUITERS(2),
  ...
```

prior to this change, the result would have been "1" or "2."  With this change, it is now a 0 or 1.  I've taken out the Integer.class from our code, but it was a bit of a sneaky gotcha when upgrading Jackson.  Ideally I would think that we'd want the result to be 1 or 2, without the quotes?

**Comment by cowtowncoder** [comment]
@kwinter I am guessing this is due to combination of things, and specifically indication that `Enum` is to be serialized as a number suggests to Jackson that the `index` should be used, and textual value ignored. Jackson does not have a way to indicate numeric value override for enums.

I think the handling is not optimal, and it is unfortunate that behavior changed for existing code.
But I am not hopeful that this would be easy to resolve due to combination of pieces involved: converting from JAXB annotations to Jackson's internal types, and then passing that to JSON Schema generator.
So I think that the easiest work-around is unfortunately removal of `@XmlEnum` indicator, just like you have done.
