### ISSUE TITLE
Custom jaxb serializer ignored if other container type matches since 2.7.0

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-module-jaxb-annotations#54]
(moved from https://github.com/FasterXML/jackson/issues/46)

I am using a bean with a custom jaxb adapter:

```java
@XmlElementWrapper(name = "links")
@XmlJavaTypeAdapter(Link.JaxbAdapter.class)
@XmlElement(name = "link")
private final List<Link> links;
private final Map<String, String> map;
```

This worked fine up until the last 2.6.x release. In 2.7.0, however, it seems that the map somehow prevents the custom serialiser to be used (still works fine as long as the Map and the List don't occur in the same file). When deserialising it seems that the custom adapter is used and this does not work with the non-custom serialiser. The fact that this only works (or does not work) one direction makes it look a bit "unintended."

I created a self contained example that shows this behaviour:

https://github.com/neumayer/jackson-example

If the jackson version in the pom file is changed to 2.6.x the test passes.

Any pointers are appreciated. I can take a closer look but I need some pointers on where to look, the adapter resolution code is not something I'm particularly familiar with.

**Comment by cowtowncoder** [comment]
(by @neuamayer)

https://github.com/FasterXML/jackson-databind/commit/5ada97ce40217626cb2cdca011fe369d0be6e729

This is what causes the error. I don't fully understand how the serializer structure works. I suspect, though, that the Locking there is shared across subclasses, or rather stops the List one to be used if a Map one already exists. You commented that "per-call" locking might be needed there. Can you elaborate?

My best guess is that a "per-subtype locking" can help with this. Then again, I'm not sure the "locking" is the ideal solution in the first place, shouldn't we rather stop the recursion?

**Comment by cowtowncoder** [comment]
What is really needed here is a self-contained test.

**Comment by mleveill** [comment]
I've also run into an issue due to that commit. I've attached a failing unit test: TestAdaptersForNestedContainers.java. In my test, essentially what happens is the `@XmlJavaTypeAdapter` annotation on the `RootBean.bottom` field is ignored.

I looked at the implementation of `StdSerializer.findConvertingContentSerializer` and it appears misleading. I've pasted the interesting part below:

```
provider.setAttribute(CONVERTING_CONTENT_CONVERTER_LOCK, Boolean.TRUE);
Object convDef;
try {
    convDef = intr.findSerializationContentConverter(m);
} finally {
    provider.setAttribute(CONVERTING_CONTENT_CONVERTER_LOCK, null);
}
```

It looks like an attribute is set before `intr.findSerializationContentConverter(m);` and removed after the call completes. However, due to the implementation of `ContextAttributes.withPerCallAttribute` (which is invoked by `SerializerProvider.setAttribute`), the code in the `finally` block ends up being a no-op (the value for the `CONVERTING_CONTENT_CONVERTER_LOCK` key remains `Boolean.TRUE`). In other words, if you modify the above code to what I've pasted below, then "wtf" will be printed many times when you run the project's tests.

```
provider.setAttribute(CONVERTING_CONTENT_CONVERTER_LOCK, Boolean.TRUE);
Object convDef;
try {
    convDef = intr.findSerializationContentConverter(m);
} finally {
    provider.setAttribute(CONVERTING_CONTENT_CONVERTER_LOCK, null);

    // Code I added:
    if (provider.getAttribute(CONVERTING_CONTENT_CONVERTER_LOCK) != null) {
        System.err.println("wtf");
    }
}
```

I changed
`provider.setAttribute(CONVERTING_CONTENT_CONVERTER_LOCK, null);`
to
`provider.setAttribute(CONVERTING_CONTENT_CONVERTER_LOCK, Boolean.FALSE);`
and my test passes, but then another existing test fails: TestConvertingSerializer.java.

I also tried removing the `provider.setAttribute` and `provider.getAttribute` calls in `StdSerializer.findConvertingContentSerializer`. This makes my test pass, but TestConvertingSerializer.java fails again. I suspect removing these calls will be necessary and another solution will be needed to solve the infinite recursion problem experienced in TestConvertingSerializer.java.

[code.zip](https://github.com/FasterXML/jackson-module-jaxb-annotations/files/217559/code.zip)

**Comment by cowtowncoder** [comment]
@mleveill good detective work. Yes, I can see why combination of things (including difference between `null` as missing, vs. opaque blocking value) would be problematic here. My only concern here is whether what you see, and original reported problem are the same. But I guess I can start by assuming it is the same thing.

**Comment by cowtowncoder** [comment]
Oh the irony: bug in clearing actually caused the test to pass... :-(

I'll first try to figure out why masking with `null` is not working as it ought to, and hope to figure out how to fix the recursion problem here.

**Comment by cowtowncoder** [comment]
I am able to fix the problem with context attributes (and it is a real flaw). This will then re-surface #357. But at least it should resolve collateral fail here.

**Comment by cowtowncoder** [comment]
@mleveill I checked in the fix for `jackson-databind`; it should remove accidental lock leftover.

**Comment by cowtowncoder** [comment]
Ok. I _think_ this issue is now resolved, although in the process another "fixed" issue become open again.

**Comment by neumayer** [comment]
Oh, I didn't get notifications for this (because the issue was moved maybe?).

Anyway, I idependently tried to upgrade to 2.8.0. today and noticed the serialisation works for me now and I wanted to report back. I have not spent any more time investigating the initial issue though.

**Comment by cowtowncoder** [comment]
@neumayer Sounds good (working with 2.8.0 part).
