### ISSUE TITLE
Bug: JAXB generated enums not serialized/ deserialized correctly

### ISSUE THREAD

**Issue by puce77** [FasterXML/jackson-module-jaxb-annotations#58]
JAXB generated Enums get serialized/ deserialized by the enum constant name instead of the generated enum constant value.

**Comment by cowtowncoder** [comment]
I would need a reproduction here; as well as note on version tested with (I assume 2.7.4 unless ortherwise noted).

**Comment by puce77** [comment]
Here is some sample code showing the issue: https://gist.github.com/puce77/a8a2e1733eac85221131720638cac788

**Comment by puce77** [comment]
Yes, I've tested it with version  2.7.4 as well.

**Comment by cowtowncoder** [comment]
@puce77 I appreciate addition of the test, but since I do not use JAXB myself pieces are not quite enough to get an actual failing test. Would it be possible to perhaps just include generate sources (I assume JAXB 2 does allow sources to be produced, not just classes). Jackson JAXB module does not make any use of XML Schema, it only looks at annotations in classes (and not in package).

**Comment by cowtowncoder** [comment]
Project moved: may be re-filed at 

https://github.com/FasterXML/jackson-modules-base/issues

if problem still occurs.
